import React, { useState } from 'react';
import { answerAPI } from '@/services/api';
import { Sparkles, Loader2, Volume2, Copy, Check } from 'lucide-react';

const AnswerGenerator = ({ userId, language }) => {
  const [question, setQuestion] = useState('');
  const [generatedAnswer, setGeneratedAnswer] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    if (!question.trim()) {
      alert('Please enter a question');
      return;
    }

    setLoading(true);
    try {
      const response = await answerAPI.generateAnswer(question, language);
      setGeneratedAnswer(response.answer);
    } catch (error) {
      console.error('Error generating answer:', error);
      alert('Failed to generate answer. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedAnswer);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSpeak = async () => {
    if ('speechSynthesis' in window) {
      const utterance = new SpeechSynthesisUtterance(generatedAnswer);
      utterance.lang = language === 'hindi' ? 'hi-IN' : 'en-US';
      window.speechSynthesis.speak(utterance);
    } else {
      alert('Text-to-speech not supported in your browser');
    }
  };

  const sampleQuestions = [
    "Discuss the role of the Indian National Congress in the freedom struggle. (250 words)",
    "Examine the significance of the Right to Constitutional Remedies. (250 words)",
    "Analyze the impact of climate change on agriculture in India. (250 words)",
    "Evaluate the role of women in India's freedom struggle. (250 words)"
  ];

  return (
    <div className="max-w-5xl mx-auto space-y-6" data-testid="answer-generator-page">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-gray-900 flex items-center space-x-2">
          <Sparkles className="h-8 w-8 text-indigo-600" />
          <span>AI Answer Generator</span>
        </h1>
        <p className="text-gray-600 mt-1">Get structured UPSC answers generated by AI</p>
      </div>

      {/* Question Input */}
      <div className="bg-white rounded-xl p-6 shadow-md">
        <label className="block text-sm font-medium text-gray-700 mb-2">
          Enter Your Question
        </label>
        <textarea
          data-testid="question-input"
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          placeholder="Example: Discuss the role of the Indian National Congress in the freedom struggle. (250 words)"
          className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 resize-none"
          rows={4}
        />

        <div className="flex items-center justify-between mt-4">
          <div className="text-sm text-gray-500">
            Language: <span className="font-medium capitalize">{language}</span>
          </div>
          <button
            data-testid="generate-button"
            onClick={handleGenerate}
            disabled={loading || !question.trim()}
            className="px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:bg-gray-400 disabled:cursor-not-allowed flex items-center space-x-2 transition-colors"
          >
            {loading ? (
              <>
                <Loader2 className="h-5 w-5 animate-spin" />
                <span>Generating...</span>
              </>
            ) : (
              <>
                <Sparkles className="h-5 w-5" />
                <span>Generate Answer</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Sample Questions */}
      <div className="bg-blue-50 rounded-xl p-6 border border-blue-200">
        <h3 className="font-medium text-gray-900 mb-3">Sample Questions (Click to use)</h3>
        <div className="space-y-2">
          {sampleQuestions.map((q, index) => (
            <button
              key={index}
              onClick={() => setQuestion(q)}
              className="w-full text-left px-4 py-2 bg-white rounded-lg hover:bg-blue-100 transition-colors text-sm text-gray-700"
            >
              {index + 1}. {q}
            </button>
          ))}
        </div>
      </div>

      {/* Generated Answer */}
      {generatedAnswer && (
        <div className="bg-white rounded-xl p-6 shadow-md" data-testid="generated-answer">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-xl font-semibold text-gray-900">Generated Answer</h3>
            <div className="flex space-x-2">
              <button
                data-testid="speak-button"
                onClick={handleSpeak}
                className="p-2 text-gray-600 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"
                title="Read aloud"
              >
                <Volume2 className="h-5 w-5" />
              </button>
              <button
                data-testid="copy-button"
                onClick={handleCopy}
                className="p-2 text-gray-600 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"
                title="Copy to clipboard"
              >
                {copied ? <Check className="h-5 w-5 text-green-600" /> : <Copy className="h-5 w-5" />}
              </button>
            </div>
          </div>
          
          <div className="prose prose-sm max-w-none">
            <div className="whitespace-pre-line text-gray-700 leading-relaxed">
              {generatedAnswer}
            </div>
          </div>

          <div className="mt-6 pt-4 border-t border-gray-200">
            <p className="text-sm text-gray-600">
              💡 <strong>Tip:</strong> Use this as a reference to understand answer structure. Practice writing your own answers for better retention.
            </p>
          </div>
        </div>
      )}

      {/* Info Box */}
      <div className="bg-gradient-to-r from-purple-50 to-indigo-50 rounded-xl p-6 border border-purple-200">
        <h3 className="font-semibold text-gray-900 mb-2">How to Use</h3>
        <ul className="space-y-2 text-sm text-gray-700">
          <li className="flex items-start">
            <span className="text-indigo-600 mr-2">1.</span>
            <span>Enter your UPSC question or select from samples</span>
          </li>
          <li className="flex items-start">
            <span className="text-indigo-600 mr-2">2.</span>
            <span>Click "Generate Answer" to get AI-powered structured answer</span>
          </li>
          <li className="flex items-start">
            <span className="text-indigo-600 mr-2">3.</span>
            <span>Study the structure: Introduction → Body → Conclusion</span>
          </li>
          <li className="flex items-start">
            <span className="text-indigo-600 mr-2">4.</span>
            <span>Use voice feature to hear the answer or copy for practice</span>
          </li>
        </ul>
      </div>
    </div>
  );
};

export default AnswerGenerator;